/*
* generated by Xtext
*/
package ch.ethz.inf.vs.akc.ui.contentassist;

import ch.ethz.inf.vs.akc.ui.contentassist.AbstractConfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConfigProposalProvider extends AbstractConfigProposalProvider {

}
