/*
* generated by Xtext
*/
package ch.ethz.inf.vs.akc.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ConfigTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
