/*
 * generated by Xtext
 */
package ch.ethz.inf.vs.akc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigUiModule extends ch.ethz.inf.vs.akc.ui.AbstractConfigUiModule {
	public ConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
