/*
 * generated by Xtext
 */
package ch.ethz.inf.vs.akc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigRuntimeModule extends ch.ethz.inf.vs.akc.AbstractConfigRuntimeModule {

}
